In [1]:
import lancedb
from dotenv import load_dotenv

load_dotenv()

db = lancedb.connect(uri = "../knowledge_base")
db

c:\Users\aless\Documents\RAG_mlops25\rag\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

LanceDBConnection(c:\Users\aless\Documents\RAG_mlops25\rag\src\rag\explorations\..\knowledge_base)

In [2]:
db["articles"]

LanceTable(connection=LanceDBConnection(c:\Users\aless\Documents\RAG_mlops25\rag\src\rag\explorations\..\knowledge_base), name="articles")

In [3]:
db["articles"].to_pandas()

,document_name,filepath,content,embedding
0,crabs.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"Crabs are decapod crustaceans, either the Brac...","[0.03024292, -0.005657196, -0.005947113, -0.04..."
1,fisk.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"A fish is an aquatic, anamniotic, gill-bearing...","[0.029907227, -0.01838684, 0.027557373, 0.0026..."
2,kanin.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"Rabbits, or bunnies, are small mammals in the ...","[0.030853271, -0.016906738, 0.044555664, -0.07..."
3,panda.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"The giant panda (Ailuropoda melanoleuca), also...","[0.0068626404, 0.062927246, 0.013130188, -0.02..."
4,tiger.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,The tiger (Panthera tigris) is a large cat and...,"[0.03564453, -0.02545166, 0.010604858, -0.0251..."

In [4]:
db["articles"].search("vad äter pandor?").to_pandas()

,document_name,filepath,content,embedding,_distance
0,panda.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"The giant panda (Ailuropoda melanoleuca), also...","[0.0068626404, 0.062927246, 0.013130188, -0.02...",0.987525
1,tiger.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,The tiger (Panthera tigris) is a large cat and...,"[0.03564453, -0.02545166, 0.010604858, -0.0251...",1.247024
2,crabs.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"Crabs are decapod crustaceans, either the Brac...","[0.03024292, -0.005657196, -0.005947113, -0.04...",1.411155
3,fisk.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"A fish is an aquatic, anamniotic, gill-bearing...","[0.029907227, -0.01838684, 0.027557373, 0.0026...",1.477388
4,kanin.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"Rabbits, or bunnies, are small mammals in the ...","[0.030853271, -0.016906738, 0.044555664, -0.07...",1.527275