In [1]:
import lancedb
from dotenv import load_dotenv

load_dotenv()

db = lancedb.connect(uri = "../knowledge_base")
db

c:\Users\aless\Documents\RAG_mlops25\rag\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

LanceDBConnection(c:\Users\aless\Documents\RAG_mlops25\rag\src\rag\explorations\..\knowledge_base)

In [3]:
db["articles"]

LanceTable(connection=LanceDBConnection(c:\Users\aless\Documents\RAG_mlops25\rag\src\rag\explorations\..\knowledge_base), name="articles")

In [4]:
db["articles"].to_pandas()

,document_name,filepath,content,embedding
0,crabs.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"Crabs are decapod crustaceans, either the Brac...","[0.03024292, -0.005657196, -0.005947113, -0.04..."
1,fisk.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"A fish is an aquatic, anamniotic, gill-bearing...","[0.029876709, -0.01838684, 0.027557373, 0.0026..."

In [5]:
db["articles"].search("vad äter pandor?").to_pandas()

,document_name,filepath,content,embedding,_distance
0,crabs.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"Crabs are decapod crustaceans, either the Brac...","[0.03024292, -0.005657196, -0.005947113, -0.04...",1.411180
1,fisk.txt,C:\Users\aless\Documents\RAG_mlops25\rag\src\r...,"A fish is an aquatic, anamniotic, gill-bearing...","[0.029876709, -0.01838684, 0.027557373, 0.0026...",1.477335